name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: mymindstorm/setup-emsdk@v14
      - name: Verify
        run: emcc -v
      
      - name: Build
        run: |
          ls ./
          for dir in ./*
          do
          if [[ -d "$dir" && "$dir" != "./base" ]]
          then
            echo "processing $dir"
            emcc $dir/main.cpp -o $dir/main.js \
            -s EXPORTED_FUNCTIONS="['_malloc','_free','ccall','allocate','UTF8ToString','intArrayFromString']" \
            -s WASM=1
            ls $dir
          fi
          done

      - name: Push
        run: |
          git add .
          git commit -m "[Github Actions] Build JS Files"
          git push
